public enum  EffectAttribures {
    WATER, FIRE, AIR, EARTH, COLD, ELECTRICITY, POISON, DARK, LIGHT, PHYSICS,
    CRIT, BLOCK, MAGIC_SHIELD, DODGE, MELEE_ATTACK, AUTO_GENERATED, ROW_DAMAGE, PIRCING_DAMAGE
}
