public enum MessageType {
    FIGHT_FINISH_HERO_WINS,

    OPEN_INVENTORY,
    CLOSE_INVENTORY,
    SELECT_HERO,
    SELECT_PLACE,

    OPEN_FIGHT_MAP,
    CLOSE_FIGHT_MAP,
    INIT_FIGHT_MAP,

    OPEN_MAIN_MENU,
    CLOSE_MAIN_MENU,

    OPEN_FIGHT_SCENE,
    CLOSE_FIGHT_SCENE,

    OPEN_FIGHT_RESULT,
    CLOSE_FIGHT_RESULT,

    OPEN_SKILLS,
    CLOSE_SKILLS,

    OPEN_POSITIONS,
    CLOSE_POSITIONS,

    OPEN_SHOP,
    CLOSE_SHOP,
    GENERATE_SHOP,
    SELECT_SHOP_ITEM,
    SELL_SHOP_ITEM,

    OPEN_MISSION_RESULT,
    CLOSE_MISSION_RESULT,

    OPEN_START_NEW_GAME,
    CLOSE_START_NEW_GAME,

    OPEN_LOAD_GAME,
    CLOSE_LOAD_GAME,
    LOAD_SAVED_GAME,
    READ_SAVED_GAME,
    START_NEW_GAME,
    SAVE_GAME
}
