public enum MessageType {
    FIGHT_FINISH_HERO_WINS,

    OPEN_INVENTORY,
    CLOSE_INVENTORY,

    OPEN_FIGHT_MAP,
    CLOSE_FIGHT_MAP,
    INIT_FIGHT_MAP,

    OPEN_MAIN_MENU,
    CLOSE_MAIN_MENU,

    OPEN_FIGHT_SCENE,
    CLOSE_FIGHT_SCENE,

    OPEN_FIGHT_RESULT,
    CLOSE_FIGHT_RESULT,

    OPEN_SKILLS,
    CLOSE_SKILLS,

    OPEN_POSITIONS,
    CLOSE_POSITIONS
}
